<?php
/**
 * 定義 & 初期処理 デモ用
 */

// assetsへのURI
define('C_ASSETS_URI', '/samples/pr_view/assets');

// 共通テンプレートへのPATH
define('C_GLOBAL_TEMPLATE_PATH', '/var/www/html/samples/pr_view/tpl');

// テンプレートファイル名
$v_htmlTpl = 'htmlheader.tpl';
$v_headerTpl = 'header.tpl';
$v_leftTpl = 'left.tpl';
$v_centerLTpl = 'centerL.tpl';
$v_centerRTpl = 'centerR.tpl';
$v_footerTpl = 'footer.tpl';
$v_spTpl = 'script.tpl';

// デモ用
$v_demo = true;
?>